### ISSUE TITLE
Highlights do not show for second work experience

### ISSUE THREAD

**Issue by qualitydixon** [francescoes/jsonresume-theme-stackoverflow#1]
Under work experience, the highlights only appear for the first work entry. Seems like this is by design to make each section collapsible but clicking the expand/collapse icon does nothing.

**Comment by francescoes** [comment]
thanks for the input, I will check it out this weekend

**Comment by qualitydixon** [comment]
Thanks for making this template. It's the best one out there.

**Comment by francescoes** [comment]
it should be fixed now, check it again. I also added more precise instruction to launch the theme.
Thanks for your support.
