### ISSUE TITLE
No level bar in language section

### ISSUE THREAD

**Issue by pabit** [francescoes/jsonresume-theme-stackoverflow#12]
**my resume.hbs**
` {{#if resume.languages.length}}
				<section class="section margin1">
					<header>
						<h2 class='section-title'>Języki</h2>
					</header>
					<section id="languages">
						{{#each resume.languages}}
							<div class="display">
								{{#if language}}
										<h3 class="language">
											{{language}}
										</h3>
								{{/if}}
								<div class="item">
									{{#if fluency}}
										<div class="level fluency {{toLowerCase fluency}}">
											<em>{{fluency}}</em>
											<div class="bar"></div>
										</div>
									{{/if}}
								</div>
							</div>
						{{/each}}
					</section>
				</section>
			{{/if}}`

**my cv.json:**

`"languages": [
      {
        "language": "Angielski",
        "level": "Native speaker"
      }
    ],`

**style.css:**

`/* Skill chart */
.level {
    margin-bottom: .5em;
}

.level .bar {
    border: 1px solid #ddd;
    display: block;
    width: 10em;
    height: 5px;
    position: relative;
}

.level .bar::after {
    position: absolute;
    content: " ";
    top: 0;
    left: 0;
    background: black;
    height: 5px;
}

.level.beginner .bar::after {
    background: #EB5F51;
    width: 2.5em;
}

.level.intermediate .bar::after {
    background: #ffdf1f;
    width: 5em;
}

.level.advanced .bar::after,
.level.fluent .bar::after {
    background: #5CB85C;
    width: 7.5em;
}

.level.master .bar::after,
.level.native.speaker .bar::after {
    background: #59C596;
    width: 10em;
}

#references .item {
    padding-left: .5em;
    border-left: 5px solid #ff6d1f;
}`

**Comment by francescoes** [comment]
Could you provide a screenshot of this part? For me looks like working

**Comment by pabit** [comment]
hi, 
Nevermind, i don`t no how but i fix this in css
