### ISSUE TITLE
Can't find social profile icon URL

### ISSUE THREAD

**Issue by arpitjindal97** [francescoes/jsonresume-theme-stackoverflow#22]
I looked into the source code but didn't find the url from where the profile icon image is coming.

**Comment by mrbabbs** [comment]
There is no prefixed URL in the code, you need to specify one in the **resume.json** file before building the resume.
The picture URL can be specified with **baiscs.picture** in the json file.

If you search in the code for **theme/partials/basics.hbs**, you will see that the attribute **src** of the tag image contains something like **{{picture}}**, this will be replaced with the URL you have specified.

**Comment by arpitjindal97** [comment]
Thanks @mrbabbs for helping me out but you misunderstood it. I was asking about the icons of social account of the user. I forgot to mention `social` keyword in title.

See the below screenshot, I want to know from where the images are getting loaded. As you can see one of my profile is missing icon. I will create PR on the repo to add the icon for the same.

![screenshot from 2017-08-25 17-14-01](https://user-images.githubusercontent.com/15676216/29712792-3da453a8-89b9-11e7-8f87-4000b60fb860.png)

**Comment by mrbabbs** [comment]
@arpitjindal97 ah ok, so forget what I said before.
Anyway this social icons come from [fontawesome.io](http://fontawesome.io/icons/), so they are font characters not image, you can inspect the code and see in the html that they are just css classes with a defined content property.

Which kind of social profile is missing?

**Comment by arpitjindal97** [comment]
[Telegram](https://telegram.org/) is missing.

**Comment by arpitjindal97** [comment]
I found the way to make it visible. The font-awesome-min.css cdn is of version 4.4.0 but telegram was added in 4.7.0 so changing the version will do the job.

**Comment by mrbabbs** [comment]
It would be nice if you can open a pull request with the updated version of the font-awsome.
Please use this issue number for the PR in this way they are attached
